behaviors:
  ShipBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 1.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.0
    max_steps: 300000
    time_horizon: 96
    summary_freq: 1000